@host=https://localhost:7226

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwM2E2M2YzNy01OTMxLTRlMmUtODgxOS1lOTMwYTZjZmVmODQiLCJnaXZlbl9uYW1lIjoiQXnFn2UiLCJmYW1pbHlfbmFtZSI6IkZhdG1hIiwianRpIjoiODI5MTNjNDgtNjg2Zi00ODcwLTliNDgtNzM4NjljYTc1MGY3IiwiZXhwIjoxNjk3MDQ5NDA5LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.5bTMZ9xg63uz8cFpQ-efF3-wHwek4pHwQ2lrR0Onysc