@host=https://localhost:7226


POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName":"Ayşe",
    "lastName":"Fatma",
    "email":"email@emaiol.com",
    "password":"password"
}